okta/okta-idx-java

README.md, examples/src/main/java/Quickstart.java, examples/src/main/java/ReadmeSnippets.java
- Added code snippets for Enroll Authenticator use cases
- Refinements done and aligned wording with dotnet SDK's readme (https://github.com/okta/okta-idx-dotnet/pull/7).
=> readme updates

api/pom.xml, coverage/pom.xml, examples/pom.xml, impl/pom.xml, integration-tests/pom.xml, pom.xml
Release version `0.1.0-beta.5` and set `0.1.0-beta.6-SNAPSHOT` dev version.
=> Release pr 0.1.0 beta.5

api/src/main/java/com/okta/idx/sdk/api/model/RemediationOption.java
See https://github.com/okta/oss-technical-designs/pull/33
=> Added type field to RemediationOption

api/src/main/java/com/okta/idx/sdk/api/wrapper/AuthenticationWrapper.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LogoutController.java
- Improved exception handling and refactored code around it.
- Logout controller will fetch `TokenResponse` from session (instead of `AuthenticationResponse` wrapper object).
=> Improved error handling

api/src/main/java/com/okta/idx/sdk/api/model/AuthenticatorType.java, api/src/main/java/com/okta/idx/sdk/api/model/IDXClientContext.java, api/src/main/java/com/okta/idx/sdk/api/wrapper/AuthenticationWrapper.java, direct-auth-samples/src/main/java/com/okta/spring/example/config/ApplicationConfig.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java, direct-auth-samples/src/main/java/com/okta/spring/example/helpers/HomeHelper.java, direct-auth-samples/src/main/resources/application.yml, direct-auth-samples/src/main/resources/templates/change-password.html, direct-auth-samples/src/main/resources/templates/enroll-authenticators.html, direct-auth-samples/src/main/resources/templates/forgot-password.html, direct-auth-samples/src/main/resources/templates/fragments/footer.html, direct-auth-samples/src/main/resources/templates/fragments/header.html, direct-auth-samples/src/main/resources/templates/home.html, direct-auth-samples/src/main/resources/templates/login.html, direct-auth-samples/src/main/resources/templates/password-authenticator-enrollment.html, direct-auth-samples/src/main/resources/templates/register.html, direct-auth-samples/src/main/resources/templates/verify-email-authenticator-enrollment.html, direct-auth-samples/src/main/resources/templates/verify.html, examples/src/main/java/Quickstart.java, impl/src/main/java/com/okta/idx/sdk/impl/client/BaseIDXClient.java, impl/src/test/groovy/com/okta/idx/sdk/impl/client/BaseIDXClientTest.groovy
**What is done?**
- Added `codeChallenge` parameter to the IDXClientContext. Refactored unit tests per this change.
- `AccessTokenVerifier` is now configured to use the autowired `issuer` and `clientId` values.
- Improved error reporting in the `LoginController` of `direct-auth` sample.
- Added reverse lookup capability for `AuthenticatorType` enum.
- Updated Quickstart recover password example.
- Updated license headers.
=> misc improvements

api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/RemediationType.java
=> OKTA-390557: handle recovery password one step identify

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java
This is reusing all the existing views from the sample, and the existing changePassword method in the SDK.
=> Add support for reenroll-authenticator (change password) during authentication.

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java
- Currently we assume that "challenge-authenticator" password remediation will be returned after "identify"
- But if admin changes app sign-on policy from "password" to "any 1 factor" the remediation after "identify" will be "select-authenticator-authenticate" which is handled in this PR
=> Handles login in the case of Any 1 factor type app sign-on rule

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java, direct-auth-samples/src/main/resources/templates/phone-authenticator-enrollment.html
We should show the home page (instead of the login page shown presently) if we have the token after skip step.
=> Enhancement: Land in home page after skip if token is present

api/src/test/groovy/com/okta/idx/sdk/api/client/AuthenticationWrapperTest.groovy
UT for AuthenticationWrapper: Self Service Registration Scenario
=> Registration UT

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java
This was erroring out for 2FA during authenticate.
=> Support selecting an authenticator for both enroll and authenticate.

api/src/test/groovy/com/okta/idx/sdk/api/client/AuthenticationWrapperTest.groovy
Fix UT register after code refactoring
=> fix register UT

api/src/test/groovy/com/okta/idx/sdk/api/client/AuthenticationWrapperTest.groovy, api/src/test/resources/introspect-response.json, api/src/test/resources/recover-transaction-response.json
UT for password recovery scenario
=> UT for password recovery scenario

direct-auth-samples/src/main/java/com/okta/spring/example/helpers/HomeHelper.java, direct-auth-samples/src/main/resources/templates/home.html
=> Display profile info on home page 

direct-auth-samples/src/main/resources/templates/index.html
=> UX enhancement

api/src/test/groovy/com/okta/idx/sdk/api/client/AuthenticationWrapperTest.groovy, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/challenge-identify-first-factor-response.json, api/src/test/resources/challenge-identify-first-response.json, api/src/test/resources/identify-error-response.json, api/src/test/resources/identify-first-error-response.json, api/src/test/resources/identify-first-factor-password-response.json, api/src/test/resources/identify-first-success-response.json, api/src/test/resources/introspect-identify-first-response.json
Authentication UTs:
- Identify In One Step
- Identify First
- Identify First + 1 Factor
- Identify First + 1 Factor Password
AuthenticationWrapperTest is renamed to IDXAuthenticationWrapperTest to be consistent
=> Authenticate UTs

api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy
=> IDXAuthenticationWrapper UTs refactoring

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/Idp.java, api/src/main/java/com/okta/idx/sdk/api/model/RemediationOption.java, api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/HomeController.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java, direct-auth-samples/src/main/resources/templates/error.html, direct-auth-samples/src/main/resources/templates/index.html, direct-auth-samples/src/main/resources/templates/login-with-idp.html, direct-auth-samples/src/main/resources/templates/login.html
=> POC - Add social login

api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/answer-challenge-identify-first-response.json, api/src/test/resources/enroll-profile-error-response.json, api/src/test/resources/recover-identify-first-response.json
UTs updated
- register fail UT added
- basic UT for IDXAuthenticationWrapper added
- Verify Email Success UT added
- Recover Password Identify First UT added
=> UTs updated

.travis.yml, THIRD-PARTY-NOTICES, api/src/test/groovy/com/okta/idx/sdk/api/client/DefaultIDXClientBuilderTest.groovy, direct-auth-samples/pom.xml, direct-auth-samples/src/test/java/env/CucumberIntegrationIT.java, direct-auth-samples/src/test/java/env/CucumberRoot.java, direct-auth-samples/src/test/java/env/DriverUtil.java, direct-auth-samples/src/test/java/env/TestApplication.java, direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefintions/UserStepDefinitions.java, src/ci/build.sh, src/ci/download_chromedriver.sh
To run the tests locally, do the following 
```
cd okta-idx-java
./src/ci/download_chromedriver.sh
mvn install -Pci
```
`download_chromedriver.sh` will download the chromedriver based on your OS and chrome version. Tests will not run unless we run this script.
=> Start the app server before Cucumber ITs are run

.gitignore, direct-auth-samples/src/main/resources/templates/login.html, direct-auth-samples/src/test/README.md, direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefintions/UserStepDefinitions.java, direct-auth-samples/src/test/resources/features/login.feature
- Adds README to explain how to run and add tests
- Adds more scenarios to login feature
=> Adds more tests to login feature

README.md, direct-auth-samples/README.md, direct-auth-samples/pom.xml
- Added Maven Profile to Cucumber ITs - so they can be optionally skipped with a `-P '!cucumber-it'` if needed.
- Updated README files.
=> Add Maven Profile to Cucumber ITs

api/src/test/groovy/com/okta/idx/sdk/api/client/DefaultIDXClientBuilderTest.groovy, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java, direct-auth-samples/src/main/java/com/okta/spring/example/helpers/ResponseHandler.java, direct-auth-samples/src/main/resources/templates/register-phone.html, direct-auth-samples/src/main/resources/templates/select-authenticator.html, direct-auth-samples/src/main/resources/templates/select-factor.html, direct-auth-samples/src/main/resources/templates/select-phone-factor.html
- SMS/Voice Factors are now nested into Phone Authenticator.
- Skip capability added in UI.
- Fixes issue in OKTA-398170
=> Nest factors into authenticators + add skip button in UI

direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java, direct-auth-samples/src/main/java/com/okta/spring/example/helpers/Util.java, direct-auth-samples/src/main/resources/templates/home.html, direct-auth-samples/src/main/resources/templates/register-phone.html
Address UX issue for below case:
`select sms -> get phone number screen -> enter invalid phone -> see error -> enter correct phone number -> goes back to select sms screen (instead of directly going to verify code screen)`
Also, the phone number validation will be done in front-end and the form submission would be prevented until the user enters a valid phone number.
=> Address UX issue

direct-auth-samples/src/main/java/com/okta/spring/example/controllers/HomeController.java
Controller can now handle callback (from social IDP) URL of pattern `http://localhost/**/callback`
=> Add callback url handling to controller

direct-auth-samples/src/main/resources/templates/login.html, direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefintions/UserStepDefinitions.java, direct-auth-samples/src/test/resources/features/login.feature, direct-auth-samples/src/test/resources/features/social-auth.feature
- Test org has been updated to allow facebook login
- Test user account created and added to travis
=> Adds Facebook login E2E test

direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefintions/UserStepDefinitions.java, direct-auth-samples/src/test/java/pages/RootPage.java, direct-auth-samples/src/test/resources/features/login.feature, direct-auth-samples/src/test/resources/features/root_page.feature
Created scenario 0.1.1. Started to use page object.
=> Kd e2e cucumber scenario 011 okta 397801

direct-auth-samples/pom.xml, direct-auth-samples/src/test/java/env/Hooks.java, direct-auth-samples/src/test/java/env/a18n/client/BaseA18NClient.java, direct-auth-samples/src/test/java/env/a18n/client/response/A18NEmail.java, direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefinitions/CommonSteps.java, direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefinitions/PasswordRecovery.java, direct-auth-samples/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, direct-auth-samples/src/test/java/pages/Page.java, direct-auth-samples/src/test/java/pages/PasswordRecoveryPage.java, direct-auth-samples/src/test/java/pages/RootPage.java, direct-auth-samples/src/test/resources/features/self_service_password_recovery.feature, direct-auth-samples/src/test/resources/features/self_service_registration.feature
What is done:
- E2E for Scenario 3.1.1
- Adding and Removing Okta user for scenarios 3.X
- Removing newly registered users in scenarios 4.X
- More logs
New Env variables are required:
- OKTA_CLIENT_CLIENTID
- OKTA_CLIENT_ORGURL
- OKTA_CLIENT_TOKEN
=> E2E for Scenario 3.1.1

.travis.yml, THIRD-PARTY-NOTICES, coverage/pom.xml, direct-auth-samples/pom.xml, integration-tests/pom.xml, pom.xml
Remove the unused `impl` & `example` module dependency from pom.
=> Cleanup deps

direct-auth-samples/src/test/java/env/a18n/client/BaseA18NClient.java, direct-auth-samples/src/test/java/env/a18n/client/response/A18NProfile.java
Pass a `displayName` JSON POST body when creating profiles
=> Pass a displayName when creating profiles

samples/embedded-auth-with-sdk/pom.xml
To unblock release, this PR will skip cucumber IT profile temporarily. Will need to revert it back after the release.
=> Skip cucumber ITs temporarily

samples/embedded-auth-with-sdk/pom.xml
=> revert skip cucumber it

.gitignore, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/MFA.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/resources/features/mfa_with_password_and_sms.feature, samples/embedded-auth-with-sdk/src/test/resources/features/self_service_registration.feature
- Handles the case where challenge-authenticator needs to be called instead of select-authenticator-authenticate
=> Fixes the Invalid operation error when invalid user tries to login in identifier first mode

api/src/main/java/com/okta/idx/sdk/api/config/OptionalPropertiesSource.java
Origin: https://github.com/okta/okta-idx-java/issues/199
=> OptionalPropertySource swallows/hides exceptions

samples/embedded-auth-with-sdk/src/main/resources/templates/login.html, samples/embedded-auth-with-sdk/src/test/java/env/CucumberIntegrationIT.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/Login.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SocialAuth.java, samples/embedded-auth-with-sdk/src/test/java/pages/OktaLoginPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/google.feature, samples/embedded-auth-with-sdk/src/test/resources/features/okta_oidc_login.feature, samples/embedded-auth-with-sdk/src/test/resources/features/okta_oidc_login_with_mfa.feature
=> Adds generic IdP button + tests for generic OIDC IdP Login (replaces social auth tests)

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/resources/templates/register.html, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/pages/RegisterPage.java
- This PR handles the case where profile enrollment policy for an app is updated to have custom attributes
- The registration form is generated dynamically by fetching userProfile from the remediation (already available wrapper method)
- /register endpoint accepts a dynamic string array instead of predefined arguments
=> Adds support for generating dynamic registration form

MIGRATING.md
=> [First DRAFT] - Added migration guide for Java Auth to IDX SDK

api/src/main/java/com/okta/idx/sdk/api/response/TokenResponse.java
=> TokenResponse public fields convert to private

README.md, api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/WrapperUtil.java, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/introspect-with-activation-token-response.json, integration-tests/src/test/groovy/com/okta/idx/sdk/tests/it/EndToEndIT.groovy, samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml
Note this PR will be merged into `rc_2.0.0` branch and moved into the main branch when the APIs officially support this feature.
=> OKTA-436460: Accept activation token

api/pom.xml, coverage/pom.xml, integration-tests/pom.xml, pom.xml, samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml, samples/pom.xml, src/owasp/owasp-suppression.xml
=> Set next major rev 2.0.0-SNAPSHOT and update few deps

THIRD-PARTY-NOTICES, pom.xml, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/resources/application.yml, samples/embedded-auth-with-sdk/src/main/resources/templates/info.html
Implemented 6.1.4 - 6.1.7 scenarios in Cucumber specs.
=> OKTA-454513: Add Magic link sample

README.md, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/resources/templates/register-google.html, samples/embedded-auth-with-sdk/src/test/java/env/Hooks.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/Login.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/PasswordRecovery.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/TotpSupport.java, samples/embedded-auth-with-sdk/src/test/java/pages/Page.java, samples/embedded-auth-with-sdk/src/test/java/pages/PasswordRecoveryPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/QrCodePage.java, samples/embedded-auth-with-sdk/src/test/java/pages/RegisterPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/SelectAuthenticatorPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/VerifyPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/facebook.feature, samples/embedded-auth-with-sdk/src/test/resources/features/google.feature, samples/embedded-auth-with-sdk/src/test/resources/features/okta_oidc_login.feature, samples/embedded-auth-with-sdk/src/test/resources/features/totp_google_authenticator.feature
Reverts okta/okta-idx-java#270
=> Revert "OKTA-456600: E2E scenarios 10.1"

api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/DefaultIDXClientBuilder.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXClientBuilder.java, api/src/main/java/com/okta/idx/sdk/api/config/ClientConfiguration.java, api/src/main/java/com/okta/idx/sdk/api/model/DeviceContext.java, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy
[Jira ticket](https://oktainc.atlassian.net/browse/OKTA-451128)
=> OKTA-451128: Allow passing device context to interact call

samples/embedded-auth-with-sdk/README.md
More developer.okta.com link fixes, including a 404.
=> Fix links/404

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java
[Jira ticket](https://oktainc.atlassian.net/browse/OKTA-465028)
=> OKTA-465028: bug fixing - enroll OktaVerify and Email [draft]

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/CurrentAuthenticatorEnrollmentValue.java, api/src/main/java/com/okta/idx/sdk/api/model/VerifyAuthenticatorAnswer.java, api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/answer-response.json, api/src/test/resources/challenge-security-question-response.json, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/ResponseHandler.java, samples/embedded-auth-with-sdk/src/main/resources/templates/verify.html
Fixing a flow where a user needs to answer the security question.
=> Fixing a flow with security question answering

samples/embedded-sign-in-widget/pom.xml, samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/OAuth2SecurityConfigurerAdapter.java, samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-sign-in-widget/src/main/resources/templates/login.html
=> OKTA-469810: fix issue with magiclink user redirection to login page

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/AuthenticatorEnrollments.java, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java
=> Add collection and stream helper methods to AuthenticatorEnrollments

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/resources/templates/select-authenticator.html, samples/embedded-auth-with-sdk/src/test/java/env/CucumberRoot.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/Login.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/MFA.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/PasswordRecovery.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SocialAuth.java, samples/embedded-auth-with-sdk/src/test/java/pages/Page.java, samples/embedded-auth-with-sdk/src/test/java/pages/PasswordRecoveryPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/RegisterPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/SelectAuthenticatorPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/VerifyPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/login.feature, samples/embedded-auth-with-sdk/src/test/resources/features/mfa_with_password_and_email.feature, samples/embedded-auth-with-sdk/src/test/resources/features/mfa_with_password_and_sms.feature, samples/embedded-auth-with-sdk/src/test/resources/features/self_service_registration.feature, samples/embedded-auth-with-sdk/src/test/resources/features/totp_google_authenticator.feature
- Adds email magic link on same browser test
- Updates the sample app and e2e tests
=> Updates the sample app and E2E tests

THIRD-PARTY-NOTICES, api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/client/ProceedContext.java, api/src/main/java/com/okta/idx/sdk/api/model/SecurityQuestion.java, api/src/main/java/com/okta/idx/sdk/api/model/VerifyAuthenticatorAnswer.java, api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/ResponseHandler.java, samples/embedded-auth-with-sdk/src/main/resources/templates/register-custom-sec-qn.html, samples/embedded-auth-with-sdk/src/main/resources/templates/register-sec-qn.html, samples/embedded-auth-with-sdk/src/main/resources/templates/select-authenticator.html
**Issues:**
OKTA-448288
OKTA-448292
E2E tests will be scoped as part of OKTA-448296, OKTA-456276, OKTA-456277, OKTA-456280
**Enroll with pre-defined security questions:**
**Enroll with custom security question (snapshot of sec qn screen alone is presented below):**
**Login with Sec Qn:**
=> Implement security qn enroll and challenge in direct-auth sample

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, samples/embedded-auth-with-sdk/src/test/java/env/Hooks.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/MFA.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/pages/LoginPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/login_id_first.feature, samples/embedded-auth-with-sdk/src/test/resources/features/self_service_registration.feature, samples/embedded-auth-with-sdk/src/test/resources/features/self_service_registration_password_optional.feature
- Adds registration and login tests for password optional feature
- Updates the embedded auth app to handle multiple authenticators available when "single factor" login policy is present
=> Adds password optional tests

samples/embedded-auth-with-sdk/pom.xml, samples/embedded-auth-with-sdk/src/test/java/env/Hooks.java, samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/pages/PasswordRecoveryPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/RegisterPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/SelectAuthenticatorPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/VerifyPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/self_service_registration.feature, samples/embedded-sign-in-widget/pom.xml
- Adds security question test to self service registration feature
=> Adds security question registration feature test

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/model/UserValue.java, api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/main/java/com/okta/idx/sdk/api/response/IDXResponse.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/scenario_6_1_3/identify-response.json
=> Expose user info in auth response

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/model/PollInfo.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy
=> poll info get refresh is now duration obj

README.md, api/pom.xml, api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/DefaultIDXClientBuilder.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXClientBuilder.java, api/src/main/java/com/okta/idx/sdk/api/config/ClientConfiguration.java, api/src/main/java/com/okta/idx/sdk/api/model/DeviceContext.java, api/src/main/java/com/okta/idx/sdk/api/model/RequestContext.java, api/src/main/resources/META-INF/okta/version.properties, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/Util.java, samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/HostedLoginCodeFlowExampleApplication.java
Fixes:
- #326 
- #301 
Tech Design [here](https://docs.google.com/document/d/1Tg4qjL2UcOEpQWCBS3ffPGPAEWqwUbNYyiyj26bi3ig/edit?usp=sharing).
=> Allow setting RequestContext per interaction and remove hardcoding of User Agent

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/client/ProceedContext.java, api/src/main/java/com/okta/idx/sdk/api/client/WrapperUtil.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/introspect-response.json
This is really just step one in a huge project that will require us to pass the correct stateHandle for every flow. Not all flows exhibit this broken behavior, so this is the one I choose to fix first.
=> Fix stateHandle passing for recoverPassword.

samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml
OKTA-500664
OKTA-500665
OKTA-500667
=> Upgrade to Spring boot 2.7.2 and Okta Spring starter 2.1.5

samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml
=> Upgraded Spring test to 5.3.22

samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/pages/VerifyPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/self_service_registration_webauthn.feature
Have updated webauthn features based on java-idx org
=> Ks okta 456564 webauthn support fix

samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/Login.java, samples/embedded-auth-with-sdk/src/test/resources/features/mfa_with_password_and_security_question.feature, samples/embedded-auth-with-sdk/src/test/resources/features/totp_google_authenticator.feature
Added fix for Google authenticator test failures in java-idx-sdk trexcloud test org
=> Added fix for Google authenticator test failures in java-idx-sdk

samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/OktaVerify.java, samples/embedded-auth-with-sdk/src/test/java/pages/OktaVerifyPage.java, samples/embedded-auth-with-sdk/src/test/java/pages/Page.java, samples/embedded-auth-with-sdk/src/test/resources/features/okta_verify.feature
Added e2e test cases for Okta Verify enrollment with SMS and Email based activation
=> Added Okta Verify enrollment with SMS and Email based activation

samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/OktaVerify.java, samples/embedded-auth-with-sdk/src/test/java/pages/OktaVerifyPage.java, samples/embedded-auth-with-sdk/src/test/resources/features/okta_verify.feature
Added Okta Verify enrollment with QR Code
=> ks-OKTA-448232-OktaVerify-EnrollmentWithQRCode

samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml
Ref: https://mvnrepository.com/artifact/junit/junit
=> upgrade junit to 5.9.0

samples/embedded-auth-with-sdk/src/test/java/pages/Page.java
Fixed Okta Verify with SMS - Test Failure
=> ks-OKTA-532257-OktaVerifySMSTestFailureFix

api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java
Fixed null pointer exception. Issue #397
=> fixed if condition to avoid null pointer exceptions

src/owasp/owasp-suppression.xml
Ref: https://github.com/jeremylong/DependencyCheck/issues/4839
=> suppress false positive cve

samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml, samples/embedded-sign-in-widget/src/test/java/env/Hooks.java, samples/embedded-sign-in-widget/src/test/java/env/a18n/client/A18NClient.java, samples/embedded-sign-in-widget/src/test/java/env/a18n/client/A18NClientBuilder.java, samples/embedded-sign-in-widget/src/test/java/env/a18n/client/BaseA18NClient.java, samples/embedded-sign-in-widget/src/test/java/env/a18n/client/DefaultA18NClientBuilder.java, samples/embedded-sign-in-widget/src/test/java/env/a18n/client/response/A18NProfile.java, samples/embedded-sign-in-widget/src/test/java/info/seleniumcucumber/userStepDefinitions/Login.java, samples/embedded-sign-in-widget/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServicePasswordReset.java, samples/embedded-sign-in-widget/src/test/java/pages/LoginPage.java, samples/embedded-sign-in-widget/src/test/java/pages/Page.java, samples/embedded-sign-in-widget/src/test/java/pages/PasswordResetPage.java, samples/embedded-sign-in-widget/src/test/resources/features/self_service_password_reset.feature, scripts/e2e-embedded-sign-in-widget.sh
Added features for ForgotPassword - embedded-sign-in-widget
=> Added features for ForgotPassword - embedded-sign-in-widget

samples/embedded-auth-with-sdk/src/test/java/info/seleniumcucumber/userStepDefinitions/SelfServiceRegistration.java, samples/embedded-auth-with-sdk/src/test/java/pages/Page.java, samples/embedded-auth-with-sdk/src/test/resources/password_optional_features/self_service_registration_password_optional.feature
Embedded-auth-with-sdk test failure fixed
=> Added fix for EmbeddedAuth test failures

THIRD-PARTY-NOTICES, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/request/EnrollUserProfileUpdateRequest.java, api/src/main/java/com/okta/idx/sdk/api/request/EnrollUserProfileUpdateRequestBuilder.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/resources/templates/register.html
=> OKTA-579868: Show password field on registration form if required by policy

api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy
=> add connection close http header

api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java
https://github.com/okta/okta-idx-java/issues/425
=> prevent npe on enroll

api/src/main/java/com/okta/idx/sdk/api/model/Age.java, api/src/main/java/com/okta/idx/sdk/api/model/Complexity.java, api/src/main/java/com/okta/idx/sdk/api/model/CurrentAuthenticatorEnrollmentValue.java, api/src/main/java/com/okta/idx/sdk/api/model/Settings.java
=> OKTA-595552: Add password requirement settings to CurrentAuthenticatorEnrollmentValue

samples/embedded-sign-in-widget/pom.xml
=> Bump `thymeleaf-extras-springsecurity5` from 3.0.4.RELEASE to 3.1.2.RELEASE

samples/embedded-sign-in-widget/pom.xml
=> Bounced `spring-security-config` from 5.7.8 to 5.8.5

api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy
=> Initialize Authentication response AuthenticationStatus to `UNKNOWN`

api/src/main/java/com/okta/idx/sdk/api/model/UserProfile.java, api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java
=> OKTA-595565: Improved UserProfile construction

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/App.java, api/src/main/java/com/okta/idx/sdk/api/model/AuthenticatorEnrollments.java, api/src/main/java/com/okta/idx/sdk/api/model/AuthenticatorType.java, api/src/main/java/com/okta/idx/sdk/api/model/Authenticators.java, api/src/main/java/com/okta/idx/sdk/api/model/Cancel.java, api/src/main/java/com/okta/idx/sdk/api/model/CurrentAuthenticatorEnrollment.java, api/src/main/java/com/okta/idx/sdk/api/model/FormValue.java, api/src/main/java/com/okta/idx/sdk/api/model/MessageValue.java, api/src/main/java/com/okta/idx/sdk/api/model/Messages.java, api/src/main/java/com/okta/idx/sdk/api/model/Options.java, api/src/main/java/com/okta/idx/sdk/api/model/OptionsFormVal.java, api/src/main/java/com/okta/idx/sdk/api/model/Recover.java, api/src/main/java/com/okta/idx/sdk/api/model/SecurityQuestion.java, api/src/main/java/com/okta/idx/sdk/api/model/SuccessResponse.java, api/src/main/java/com/okta/idx/sdk/api/model/User.java, api/src/main/java/com/okta/idx/sdk/api/model/VerifyChannelDataOptions.java
=> OKTA-595564: Refactor model APIs

pom.xml
=> Bump tomcat-embed-core from 9.0.76 to 9.0.81

samples/embedded-sign-in-widget/pom.xml
=> Update spring-security-config from 5.8.5 to 5.8.7 to fix cve

samples/embedded-auth-with-sdk/pom.xml
=> Bump org.thymeleaf:thymeleaf from 3.0.15 to 3.1.1.RELEASE

samples/embedded-auth-with-sdk/pom.xml
=> Bump thymeleaf from 3.1.1.RELEASE to 3.1.2.RELEASE

pom.xml, samples/embedded-auth-with-sdk/pom.xml, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LogoutController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/HomeHelper.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/ResponseHandler.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/Util.java, samples/embedded-sign-in-widget/pom.xml, samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/controllers/LoginController.java, samples/embedded-sign-in-widget/src/main/resources/templates/login.html
=> Fix samples

pom.xml
- Bump Jackson from 2.17.2 to 2.18.0
- Bump Snakeyaml from 2.2 to 2.3
=> Bump Jackson and Snakeyaml

samples/embedded-sign-in-widget/pom.xml
https://oktainc.atlassian.net/browse/OKTA-866257
=> OKTA-866257 - bumping up net.minidev

samples/embedded-sign-in-widget/pom.xml
https://oktainc.atlassian.net/browse/OKTA-898874
=> OKTA-898874 - bumping up spring-security-crypto

pom.xml
https://oktainc.atlassian.net/browse/OKTA-891778
=> OKTA-891778 - Outdated Library - okta/okta-idx-java@master - org.apache.tomcat.embed:tomcat-embed-core@10.1.34
