README.md, api/src/main/java/com/okta/idx/sdk/api/client/IDXClient.java, api/src/main/java/com/okta/idx/sdk/api/model/IDXClientContext.java, api/src/main/java/com/okta/idx/sdk/api/model/SuccessResponse.java, examples/src/main/java/Quickstart.java, examples/src/main/java/ReadmeSnippets.java, impl/src/main/java/com/okta/idx/sdk/impl/client/BaseIDXClient.java, impl/src/test/groovy/com/okta/idx/sdk/impl/client/BaseIDXClientTest.groovy, integration-tests/src/test/groovy/com/okta/idx/sdk/tests/it/EndToEndIT.groovy
- Update the SDK to allow for resuming a flow from any point (OKTA-362449).
- Create an immutable object of `codeVerifier` and `interactionHandle` that can be used outside of the client.
- Move the creation of `codeVerifier` into _interact_ method.
- Use the new object in _exchangeCode_ method.
- Update all ITs and UTs.
- Update README code snippets.
=> OKTA-362449: code verifier improvements

THIRD-PARTY-NOTICES, api/src/main/java/com/okta/idx/sdk/api/response/AuthenticationResponse.java, api/src/main/java/com/okta/idx/sdk/api/wrapper/AuthenticationWrapper.java, direct-auth-samples/pom.xml, direct-auth-samples/src/main/java/com/okta/spring/example/config/ApplicationConfig.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/HomeController.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java, direct-auth-samples/src/main/java/com/okta/spring/example/helpers/HomeHelper.java, direct-auth-samples/src/main/java/com/okta/spring/example/helpers/package-info.java, direct-auth-samples/src/main/resources/templates/home.html
Before this change, the response wouldn't contain tokens after enrolling the last authenticator.
Now once you've gone through a complete enrollment, the response will contain tokens you can use to act as a logged in user.
=> Exchange Tokens when all authenticators are enrolled.

impl/src/main/java/com/okta/idx/sdk/impl/client/BaseIDXClient.java, impl/src/main/java/com/okta/idx/sdk/impl/util/ClientUtil.java, impl/src/test/groovy/com/okta/idx/sdk/impl/client/BaseIDXClientTest.groovy, impl/src/test/groovy/com/okta/idx/sdk/impl/util/TestClientUtil.groovy, integration-tests/src/test/groovy/com/okta/idx/sdk/tests/it/EndToEndIT.groovy
**What's done?**
`interact` endpoint is constructed like below:
**Case-1: Root/Org Issuer**
client supplied issuer - `https://{yourOktaDomain}`
constructed interact URL - `https://{yourOktaDomain}/oauth2/v1/interact`
**Case-2: Default Issuer**
client supplied issuer - `https://{yourOktaDomain}/oauth2/default`
constructed interact URL - `https://{yourOktaDomain}/oauth2/default/v1/interact`
**Variation of Case-1 with a trailing `/`**
client supplied issuer - `https://{yourOktaDomain}/`
constructed interact URL - `https://{yourOktaDomain}/oauth2/v1/interact`
=> OKTA-388348 - fix interact uri for org AS

THIRD-PARTY-NOTICES, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/AuthenticationStatus.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java
Once skip is complete, we don't have tokens, so we can't log them in under certain circumstances. 
In this case, we just redirect them to the login page and show the message from the server.
"To finish signing in, check your email."
=> Fix skip authenticator.

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, direct-auth-samples/src/main/resources/templates/forgot-password-authenticators.html
- If app sign-on rule is set for "any 1 factor" instead of "password", we will have to handle the `select-authenticator-authenticate` remediation from `identify` request
- Also adds a small fix where at least 1 authenticator radio button for recover password screen  is checked by default. This fixes the issue where user can click "Proceed" without selecting an authenticator, causing a servlet exception.
=> Fixes failure in the case of any factor login app rule

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/AuthenticatorUIOptions.java, direct-auth-samples/src/main/java/com/okta/spring/example/controllers/LoginController.java
After this change, we would be able to propagate the below backend error to the UI for Forgot password case.
Backend error:
```
2021-05-02 22:35:46.681 ERROR 26698 --- [nio-8080-exec-8] c.o.i.s.a.c.IDXAuthenticationWrapper     : Exception occurred
com.okta.idx.sdk.api.exception.ProcessingException: Request to https://dev-30426356.okta.com/idp/idx/recover failed. HTTP status: 400
at com.okta.idx.sdk.api.client.BaseIDXClient.handleErrorResponse(BaseIDXClient.java:505) ~[okta-idx-java-api-0.1.0-beta.6-SNAPSHOT.jar:0.1.0-beta.6-SNAPSHOT]
at com.okta.idx.sdk.api.client.BaseIDXClient.recover(BaseIDXClient.java:413) ~[okta-idx-java-api-0.1.0-beta.6-SNAPSHOT.jar:0.1.0-beta.6-SNAPSHOT]
at com.okta.idx.sdk.api.model.Recover.proceed(Recover.java:72) …
```
=> Present forgot password errors to the user

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/test/groovy/com/okta/idx/sdk/api/client/AuthenticationWrapperTest.groovy
2021-05-05 13:49:34.051  INFO 59829 --- [nio-8080-exec-1] c.o.i.s.a.c.IDXAuthenticationWrapper     : Skipping unsupported authenticator - enrollmentId
=> Filter invalid methods for selecting an authenticator type.

api/src/main/java/com/okta/idx/sdk/api/client/ProceedContext.java
This is the only thing needed to get interaction_required from social auth to work.
=> Expose IDXClientContext from ProceedContext.

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/model/FormValue.java
This supports `authenticator-verification-data` for instance.
This allows us to handle `authenticator-verification-data` from authenticate for example. See https://github.com/okta/okta-idx-android/pull/33
=> Return authenticators on other statuses.

direct-auth-samples/src/main/java/com/okta/spring/example/helpers/ResponseHandler.java
If the user has only phone required rule (no email), the sample app fails with "unsupported policy".
(policy config: add the user to MFA Required and Phone Enrollment Required groups). With this config, login of a user would fail with "Unsupported Policy." error. This PR fixes it.
=> fix mfa issue

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java
Due to the way the underlying API works, we can get into a situation where the identify call succeeds, and we have a proceed context that's in the wrong state.
I originally used the begin context from the login page to optimize network calls. But it causes issues due to the way the API/SDK is implemented.
See OKTA-403240
=> Fix register after multiple attempts with invalid email.

samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/controllers/HomeController.java
If `interaction_code` and `state` query args are presented then need to exchange interaction code to a token.
=> Social auth login requires user extra click for interaction code exchange

samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/controllers/HomeController.java
Cleanup the context in case of unsuccessful login to force the idxClient to do an `interact()` again
=> fix a "Session expired" error

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/HomeHelper.java
Apparently, the `/v1/userinfo` endpoint supports both `POST` and `GET`. 
Updating it to `GET` now because [Okta official documentation](https://developer.okta.com/docs/reference/api/oidc/#userinfo) states that `GET` is supported.
=> update userinfo invocation from POST to GET

api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/model/AuthenticationOptions.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java
Related to https://github.com/okta/okta-idx-java/issues/197
- Password represented as a char[]
- NPE [credentials.setPasscode(authenticationOptions.getPassword().toCharArray())](https://github.com/okta/okta-idx-java/blob/a4f0442bcfd4bf4e91c4abc552b6799d7ae3775b/api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java#L123) solved
=> Security fix

samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/CustomAuthenticationProcessingFilter.java
- When using org authorization server, the userinfo uri returned by `clientRegistration.getProviderDetails().getUserInfoEndpoint().getUri()` is incorrect 
- The method returns `https://org.okta.com/v1/userinfo` instead of https://org.okta.com/oauth2/v1/userinfo`
- See https://oktainc.atlassian.net/browse/OKTA-414510 for more information
=> Fixes the issue with userinfo uri when using org authorization server

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/WrapperUtil.java
Making a request to `IDXAuthenticationWrapper.begin()` when Authorization Server is not configured for `Interaction Code` hides error
Origin: https://github.com/okta/okta-idx-java/issues/201
=> Hidden error

THIRD-PARTY-NOTICES, api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/ProceedContext.java, api/src/main/java/com/okta/idx/sdk/api/model/PollInfo.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, api/src/test/resources/verify-email-token-response.html, pom.xml, samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml
- Allow developers to call the `/email/verify?token=xxxxx` endpoint to verify the token in verification email.
- Expose Polling information so developers can create a polling functionality in their webapp.
=> OKTA-448501: Add supporting functions for Magic Link capabilities

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/LoginController.java
Add missing functionality to HomeController.
The action variable analysis should be performed before any other logic.
=> Fix for inability to skip 'enroll Authenticator' step during self-registration

samples/embedded-sign-in-widget/README.md
This link was not 404'ing, but the fragment being redirected to was not correct, so the topof thepage was shown, and not the relevant section. This PR fixes that.
=> Update "OIDC Web Application Setup Instructions" link

README.md
I don't think any of these actually 404'ed, but they were ending up at strange targets. This is an effort to improve things.
=> Improve links to dev.okta

src/ci/build.sh
Similar to https://github.com/okta/okta-sdk-java/pull/641
=>  stop deploying snapshot builds from travis

samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/controllers/HomeController.java
If OTP code is present need to use it for `verify` operation instead of `introspect`
=> Fix callback entry point

api/src/main/java/com/okta/idx/sdk/api/client/BaseIDXClient.java, api/src/main/java/com/okta/idx/sdk/api/client/IDXAuthenticationWrapper.java, api/src/main/java/com/okta/idx/sdk/api/util/ClientUtil.java, api/src/test/groovy/com/okta/idx/sdk/api/client/BaseIDXClientTest.groovy, api/src/test/groovy/com/okta/idx/sdk/api/util/ClientUtilTest.groovy, samples/embedded-auth-with-sdk/src/main/java/com/okta/spring/example/helpers/HomeHelper.java, samples/embedded-sign-in-widget/src/main/java/com/okta/spring/example/HelperUtil.java
At first glance it may appear that `getNormalizeUri` will normalize any URL, but it ONLY works for issuer URIs
=> Rename ClientUtil.getNormalizeUri() to ClientUril.normalizeIssuerUri to avoid confusion

THIRD-PARTY-NOTICES, pom.xml
- Upgrade to Java parent v23.
- Fix Java 17 build issue (https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options).
=> fix java 17 build issue

api/src/main/java/com/okta/idx/sdk/api/client/AuthenticationTransaction.java, api/src/main/java/com/okta/idx/sdk/api/model/I18NMessage.java, api/src/test/groovy/com/okta/idx/sdk/api/client/IDXAuthenticationWrapperTest.groovy, pom.xml, samples/embedded-sign-in-widget/pom.xml, samples/pom.xml
https://github.com/okta/okta-idx-java/issues/439
OKTA-595550
- AuthenticationREsponse will now contain i18n messages that were sent by Okta Backend in IDXResponse.
- Few dependency upgrades.
=> Include i18n messages in AuthenticationResponse object

pom.xml, src/owasp/owasp-suppression.xml
- Bump `okta-commons` from 1.3.4 to 1.3.5
- Added `CVE-2023-35116` to CVE suppression and cleaned up other unnecessary entries.
=> bump okta-commons from 1.3.4 to 1.3.5

samples/embedded-auth-with-sdk/pom.xml, samples/embedded-sign-in-widget/pom.xml
OKTA-634944
- Bump `org.thymeleaf:thymeleaf` from `3.0.15.RELEASE` to `3.1.2.RELEASE`
- Bump springboot from `2.7.12` to `2.7.15`
=> cve fix: bump org.thymeleaf from 3.0.15 to 3.1.2.RELEASE

pom.xml
This PR updates the org.springframework.security dependency from version from 11.0.6 to 11.0.8 to remediate multiple vulnerabilities identified by Snyk.
=> OKTA-959507 - bumping tomcat-embed-core to 11.0.8
